services:
  - type: web
    name: medmatch-frontend
    runtime: docker
    rootDir: medical-recruiting-platform/frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
    healthCheckPath: /health
    plan: free

  - type: web
    name: medmatch-api
    runtime: docker
    rootDir: medical-recruiting-platform/backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medmatch-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALGORITHM
        value: HS256
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://medmatch-frontend-nsuo.onrender.com
    healthCheckPath: /api/v1/health
    plan: free

databases:
  - name: medmatch-db
    databaseName: medmatch
    user: medmatch
    plan: free
